// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // CLI (migrate, studio) usa a conexão direta — pgbouncer em transaction mode
    // (porta 6543 do Supabase) não suporta prepared statements que o migrate emite.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
